# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 2000000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"

# --- Attack params ---
adv_train: False # whether use adv samples throughout the training
robust_regular: False # whether add the logit_margin regularizer
diff_regular: False
robust_lambda: 0.001

weight_td: False
weight_adv_loss: False
pareto: False
normalization_type: "loss+"

training_attack: False # during normal training, perturb the obs during the 1/3 to 2/3 of the training
test_attack: False # during testing, perturb the obs only during the 1/3 to 2/3 of the testing
all_test_attack: False # during testing, perturb the obs during the whole testing

# --- adv settings ---
niters: 1
attack_method: "noise"
epsilon: 1
verbose: False


# --- Evolution settings ---
EA: True
Pareto: True
rl_to_ea_synch_period: 1
pop_size: 20
elite_fraction: 0.2 # 0.4 default setting
mutation_prob: 0.3 # 0.5 default setting
prob_reset_and_sup: 0.05 # default setting
frac: 0.5 # 1.0 mutation alpha, see paper for details
pr_dim: 64  # default setting
EA_alpha: 1.0  # default setting
Org_alpha: 1.0 # default setting
N_type: 1 # default setting
# SAME: 1  # default setting
start_timesteps: 50000 # 50000, 1 for test, 5000000 for not enable evolution
EA_freq : 50  # 50 default setting, 1 for test
state_alpha: 0.2   # 0.1 beta control VMM, see paper for details
rl_replace_ea_synch_period: 1


run: "default"
