# --- MADDPG specific parameters ---

runner: "parallel"

buffer_size: 50000
# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

t_max: 10050000

# use the madddpg_learner to train
mac: "maddpg_mac"
reg: 0.001
batch_size: 32
lr: 0.0005
use_rnn: True

adv_eps: 0.001

batch_size: 128
batch_size_run: 8

standardise_returns: False
standardise_rewards: True
common_reward: True

learner: "m3ddpg_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
critic_type: "maddpg_critic"
name: "m3ddpg"